version: '2'

services:

  zookeeper:
    image: debezium/zookeeper:1.5
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  kafka:
    image: debezium/kafka:1.5
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181

  postgres:
    image: debezium/example-postgres:1.5
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres

  connect:
    image: debezium/connect:1.5
    ports:
     - 8083:8083
    links:
     - kafka
     - postgres
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses

  generator:
    build: ./generator
    links:
      - postgres

#список доступных библиотек
#docker run --rm streamsets/datacollector:3.9.1 stagelibs -list

  streamsets:
    build:
      context: ./streamsets
      args:
        SDC_LIBS: streamsets-datacollector-cdh_6_0-lib
        #SDC_LIBS: streamsets-datacollector-apache-kafka_2_0-lib,streamsets-datacollector-cdh_6_0-lib
    ports:
      - 18630:18630
    volumes:
      - ./streamsets/sdc-data:/data
      #- ./streamsets/sdc-stagelibs:/opt/streamsets-datacollector-3.9.1/streamsets-libs
      #- ./streamsets/sdc-stagelibs:/opt/streamsets-datacollector-3.9.1/streamsets-libs-extras

  # HDFS namenode
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    ports:
      - 9870:9870
      - 9000:9000
    # volumes:
    #   - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop/hadoop.env

  # HDFS datanode
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    # volumes:
    #   - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop/hadoop.env

# volumes:
#   hadoop_namenode:
#   hadoop_datanode:
