version: '2'

services:

  zookeeper:
    image: debezium/zookeeper:1.4
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  kafka:
    image: debezium/kafka:1.4
    ports:
     - 9092:9092
    links:
     - zookeeper
    depends_on:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181

  postgres:
    image: debezium/example-postgres:1.4
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres

  apicurio:
    image: apicurio/apicurio-registry-mem:1.3.2.Final
    ports:
      - 8080:8080
    depends_on:
     - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - REGISTRY_URL=http://apicurio:8080

  connect:
    image: debezium/connect:1.4
    ports:
     - 8083:8083
    links:
     - zookeeper
     - kafka
     - postgres
     - apicurio
    depends_on:
     - postgres
     - apicurio
    environment:
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
     - BOOTSTRAP_SERVERS=kafka:9092
     - ENABLE_APICURIO_CONVERTERS=true
     - KEY_CONVERTER=io.apicurio.registry.utils.converter.AvroConverter
     - VALUE_CONVERTER=io.apicurio.registry.utils.converter.AvroConverter
     - CONNECT_KEY_CONVERTER=io.apicurio.registry.utils.converter.AvroConverter
     - CONNECT_KEY_CONVERTER_APICURIO.REGISTRY_URL=http://apicurio:8080
     - CONNECT_KEY_CONVERTER_APICURIO.REGISTRY_GLOBAL-ID=io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
     - CONNECT_VALUE_CONVERTER=io.apicurio.registry.utils.converter.AvroConverter
     - CONNECT_VALUE_CONVERTER_APICURIO_REGISTRY_URL=http://apicurio:8080
     - CONNECT_VALUE_CONVERTER_APICURIO_REGISTRY_GLOBAL-ID=io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
    
  generator:
    build: ./generator
    links:
      - postgres
    depends_on:
      - postgres

  streamsets:
    build:
      context: ./streamsets
      args:
        SDC_LIBS: streamsets-datacollector-apache-kafka_2_6-lib,streamsets-datacollector-cdh_6_3-lib
        #SDC_LIBS: streamsets-datacollector-apache-kafka_2_0-lib,streamsets-datacollector-cdh_6_0-lib
    ports:
      - 18630:18630
    volumes:
      - ./streamsets/sdc-data:/data

  # HDFS namenode
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    ports:
      - 9870:9870
      - 9000:9000
    # volumes:
    #   - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop/hadoop.env

  # HDFS datanode
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    # volumes:
    #   - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop/hadoop.env

# volumes:
#   hadoop_namenode:
#   hadoop_datanode:
